### PR TITLE
Add MIPS cross-compilation support

### PR DESCRIPTION
**Pull request by jrhea**
This PR is adding MIPS cross-compilation support so that herumi can run on the GridPlus Lattice1.  Eventually they would like to get an Eth2 validator client running on this hardware and this is the first step.  I thought it would be best to submit a PR to this repo rather than fork so any suggestions are much appreciated.

> Note: I have one minor modification to the mcl library that i had to perform in order to get it to work.  I will submit a PR for review in the MCL repo and link to this PR.

Below are notes on how to configure a Docker image capable of performing the cross-compilation.

Docker setup notes:
```
docker pull onion/omega2-source
docker run -it onion/omega2-source /bin/bash
apt-get update && apt-get install -y git wget subversion build-essential libncurses5-dev zlib1g-dev gawk flex quilt git-core unzip libssl-dev python-dev python-pip libxml-parser-perl
make menuconfig
```

In the menu that appears, you will need to do the following:
* For Target System, select MediaTek Ralink MIPS
* For Subtarget, select MT7688 based boards
* For Target Profile, select Multiple Devices
* A new item will appear on the Main menu, Target Devices
* For Target Devices, select Onion Omega2 and Onion Omega2+
* Exit and save your configuration

```
./scripts/feeds update onion
git pull
sh scripts/onion-minimal-build.sh
make -j8
```

**Clang**

/etc/apt/sources.list
```
# i386 not available
deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main
deb-src http://apt.llvm.org/bionic/ llvm-toolchain-bionic main
# 9
deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main
deb-src http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main
# 10
deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main
deb-src http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main
```
```
apt-get install lsb-release software-properties-common
bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
apt-get install clang-format clang-tidy clang-tools clang clangd libc++-dev libc++1 libc++abi-dev libc++abi1 libclang-dev libclang1 liblldb-dev libllvm-ocaml-dev libomp-dev libomp5 lld lldb llvm-dev llvm-runtime llvm python-clang
```

**Herumi**

 ```
mkdir work
cd work
apt-get install libgmp-dev
git clone https://github.com/herumi/mcl
git clone https://github.com/herumi/bls
git clone https://github.com/herumi/bls-eth-go-binary
git clone https://github.com/herumi/cybozulib.git
cd bls-eth-go-binary
make CXX=clang++-10 mips_all
```

### CODE REVIEW

**Comment by jrhea** [comment]
BTW, I can squash some or all of the commits if needed

**Comment by alex-miller-0** [comment]
@jrhea probably best to squash. Also I wonder if the docker instructions could live somewhere in the repo? I'm not sure where that would be. Perhaps a `/doc` dir? Curious what @herumi has done to record documentation for how to cross compile the `arm64` bin (I guess I'm assuming it was xcompiled)

**Comment by herumi** [comment]
Thank you for the pull-request.
Please wait a moment to check it after I prepare the environment. 
I'll push the binary I built by myself.

I use a real arm64 Linux environment to build it instead of cross-compiling.

**Comment by jrhea** [comment]
@alex-miller-0 is more familiar with the target environment, but it should be a 32bit MIPS processor (little endian) running Linux.  If it helps, here is the output of the file command on the object files:

```
> file obj/*.o
obj/base32.o:       ELF 32-bit LSB relocatable, MIPS, MIPS32 rel2 version 1 (SYSV), not stripped
obj/bls_c384_256.o: ELF 32-bit LSB relocatable, MIPS, MIPS32 rel2 version 1 (SYSV), not stripped
obj/fp.o:           ELF 32-bit LSB relocatable, MIPS, MIPS32 rel2 version 1 (SYSV), not stripped
```

**Comment by jrhea** [comment]
@herumi fyi, i had an uncommitted change that I forgot to push until just a few minutes ago. 🤦

**Comment by jrhea** [comment]
Closing as support has been added in this commit 41fc56eba7b48e65e410ef11cf5042d62e887017

**Pull request closed without merging**
